version: '3.9'
services:
  goback:
    container_name: gotest43
    image: yunusdermawan/goapps
    ports:
      - '80012:8002'
    networks:
      - docker-go
    environment:
      - DB_HOST: 'postgres-container'

networks:
  docker-go:
    external: true